### ISSUE TITLE
Exclude generating classNames with %ad% for avoiding AdBlock blocking

### ISSUE THREAD

**Issue by Yegorich555** [shoonia/mini-css-class-name#1]
By default AdBlock (extension for Chrome) hides content with classNames like: %ad%. So it would be fine if you will add 
```js
options: 
{
  excludePattern: 'Regex expression or even function here'
}
```
or even add excluding-ad-logic by default.
For performance purpose, we can exlude 'd' and 'D' symbols from the firstChar. And do we have any ability to exclude '_' symbol?
https://www.screencast.com/t/nsrdRdd5X

**Comment by shoonia** [comment]
Hey!
Thanks for your request. It's a very bad situation with AdBlock. I will fix this at near time.

**Comment by shoonia** [comment]
Added `excludePattern` parameter in v0.6.0
```js
const generate = miniClassName({ excludePattern: /[_d]/gi });
```

**Comment by kireerik** [comment]
By the way that is not a correct way to detect an advertisement. The class name does not determine whether some content is an advertisement or not.

**Comment by kireerik** [comment]
Yes, that's what I am saying that advertisement detection (of AdBlock) is not correct.
