### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by TKDev7** [shoonia/mini-css-class-name#32]
So how does caching work here? Doesn’t it generate different class names each time I build the project? I was thinking this plugin should create a JSON file with all CSS files in your src folder and their hash. This way the hash is predictable. So something like:
```json
{
  “src/component/Button”: “a”,
  “src/component/Card”: “b”,
} 
```

**Comment by shoonia** [comment]
Hello, @MrHBS!

I thought about the cache, but it's a big task. We can get a lot of problems with the invalidation of cache.

In my projects, I'm only using the minimizer in the production build. [I have added an example to the documentation](https://github.com/shoonia/mini-css-class-name#development-and-production-environments).
