### ISSUE TITLE
Example nextjs

### ISSUE THREAD

**Issue by IRediTOTO** [shoonia/mini-css-class-name#5]
Hi, I really love this pack. Can you please make an example for Nextjs ? I don't know how to config with nextjs. 
Please please please :D

**Comment by shoonia** [comment]
Hey! @IRediTOTO 

Unfortunately, I don't have experience with Nextjs. But I see the Nextjs has config files look like in Gatsbyjs
https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

You may try creating something that looks like I did for Gatsby. 
https://github.com/shoonia/gatsby-plugin-mini-css-class-name/blob/master/gatsby-node.js

With Lodash function `cloneDeepWith()` you just a cloned part of Webpack config and for css-loader you changing the `modules` property. 

Be attention which version of css-loader using in your Nextjs
https://github.com/shoonia/mini-css-class-name#css-modules

I hope this could help you!

**next.config.js**

```js
/**
 * This config is just an example. Needs to checking
 */
const cloneDeepWith = require('lodash/cloneDeepWith');
const miniClassName = require('mini-css-class-name');

const cache = new Map();

const createLocaiIdent = (options) => {
  const generate = miniClassName(options);

  return (context, _, localName) => {
    const key = context.resourcePath + localName;

    // the same classes equal the same mini-unique class
    if (cache.has(key)) {
      return cache.get(key);
    }

    const className = generate();

    cache.set(key, className);

    return className;
  };
};

module.exports = {
  webpack: (config, { dev }) => {
    if (dev) {
      return config;
    }

    const getLocalIdent = createLocaiIdent({ /* options */ });

    config.module.rules = config.module.rules = cloneDeepWith(config.module.rules, (value, key) => {
      // This condition needs checking
      if (key === 'options' && value.modules) {
        return {
          ...value,
          modules: {
            // This code needs checking
            getLocalIdent: getLocalIdent,
          },
        };
      }
    });

    return config;
  },
};

```

**Comment by IRediTOTO** [comment]
Thank you let's me try

**Comment by shivamragnar** [comment]
Did it work?

**Comment by IRediTOTO** [comment]
No :D @shivamragnar
